import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function POST(req: Request) {
  try {
    const data = await req.json();

    // Basic validation
    if (!data || !data.games || !data.products || !data.reviews) {
      return NextResponse.json({ error: 'Invalid data format' }, { status: 400 });
    }

    const now = new Date().toLocaleString("ru");
    const content = `// Client-safe product data — no server dependencies
// Auto-generated by Admin Panel API: ${now}

export interface Settings {
  exchangeRate: number;
}

export interface PriceTier {
  label: string;
  duration: string;
  price: number;
}

export interface RegionPrice {
  region: string;
  label: string;
  priceMultiplier: number;
}

export interface Game {
  id: string;
  name: string;
  image: string;
  icon: string;
  featured: boolean;
  status: "online" | "offline" | "updating";
  description: string;
}

export interface Review {
  id: string;
  author: string;
  rating: number;
  text: string;
  createdAt: string;
}

export interface Product {
  id: string;
  name: string;
  gameId: string;
  game: string;
  categoryId: string;
  description: string;
  features: string[];
  specs: { label: string; value: string }[];
  images: string[];
  coverImage?: string;
  galleryImages?: string[];
  priceTiers: PriceTier[];
  regionPricing?: RegionPrice[];
  status: "undetected" | "detected" | "updating";
  lastUpdate: string;
  createdAt: string;
}

export const settings: Settings = ${JSON.stringify(data.settings || { exchangeRate: 76.75 }, null, 2)};

export const games: Game[] = ${JSON.stringify(data.games, null, 2)};

export const products: Product[] = ${JSON.stringify(data.products, null, 2)};

export const reviews: Review[] = ${JSON.stringify(data.reviews, null, 2)};

// Helper functions
export function getSettings(): Settings {
  return settings;
}

export function getGames(): Game[] {
  return games;
}

export function getGameById(id: string): Game | undefined {
  return games.find(g => g.id === id);
}

export function getFeaturedGames(): Game[] {
  return games.filter(g => g.featured);
}

export function getProducts(): Product[] {
  return products;
}

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductsByGame(game: string): Product[] {
  return products.filter(p => p.game === game);
}

export function getProductsByGameId(gameId: string): Product[] {
  return products.filter(p => p.gameId === gameId);
}

export function getReviews(): Review[] {
  return reviews;
}
`;

    // Path to src/lib/products-data.ts
    const filePath = path.join(process.cwd(), 'src', 'lib', 'products-data.ts');

    // Write the file
    fs.writeFileSync(filePath, content, 'utf8');

    return NextResponse.json({ success: true, message: 'Data saved successfully' });
  } catch (error) {
    console.error('Error saving data:', error);
    return NextResponse.json({ error: 'Failed to save data' }, { status: 500 });
  }
}
