"use client";

import { useState, useEffect, useCallback } from "react";
import { Product, Game, Review, PriceTier, products as defaultProducts, games as defaultGames, reviews as defaultReviews } from "@/lib/products-data";
import { Play } from "lucide-react";

// ========== EDIT TYPES ==========
interface EditGame {
  id: string;
  name: string;
  image: string;
  icon: string;
  featured: boolean;
  status: "online" | "offline" | "updating";
  description: string;
}

interface EditProduct {
  id: string;
  name: string;
  gameId: string;
  game: string;
  partner?: string;
  description: string;
  features: string;
  specs: string;
  coverImage: string;
  galleryImages: string[];
  priceTiers: PriceTier[];
  status: "undetected" | "detected" | "updating";
}

interface EditReview {
  id: string;
  author: string;
  rating: number;
  text: string;
}

function toEditProduct(p: Product): EditProduct {
  return {
    id: p.id,
    name: p.name,
    gameId: p.gameId,
    game: p.game,
    partner: p.partner || "",
    description: p.description,
    features: p.features.join("\n"),
    specs: p.specs.map(s => `${s.label}: ${s.value}`).join("\n"),
    coverImage: p.coverImage || "",
    galleryImages: [...(p.galleryImages || [])],
    priceTiers: [...p.priceTiers],
    status: p.status,
  };
}

function fromEditProduct(e: EditProduct): Product {
  return {
    id: e.id,
    name: e.name,
    gameId: e.gameId,
    game: e.game,
    partner: e.partner ? e.partner.trim() : undefined,
    categoryId: "",
    description: e.description,
    features: e.features.split("\n").map(s => s.trim()).filter(Boolean),
    specs: e.specs.split("\n").map(s => s.trim()).filter(Boolean).map(line => {
      const [label, ...rest] = line.split(":");
      return { label: label.trim(), value: rest.join(":").trim() };
    }),
    images: [],
    coverImage: e.coverImage || undefined,
    galleryImages: e.galleryImages.filter(Boolean),
    priceTiers: e.priceTiers,
    status: e.status,
    lastUpdate: new Date().toLocaleString("ru"),
    createdAt: new Date().toISOString(),
  };
}

// ========== GENERATE TS FILE CONTENT ==========
function generateTsFileContent(gamesData: Game[], productsData: Product[], reviewsData: Review[]): string {
  const now = new Date().toLocaleString("ru");
  return `// Client-safe product data — no server dependencies
// Auto-generated by Admin Panel: ${now}

export interface PriceTier {
  label: string;
  duration: string;
  price: number;
  priceUsd?: number;
}

export interface Game {
  id: string;
  name: string;
  image: string;
  icon: string;
  featured: boolean;
  status: "online" | "offline" | "updating";
  description: string;
}

export interface Review {
  id: string;
  author: string;
  rating: number;
  text: string;
  createdAt: string;
}

export interface Product {
  id: string;
  name: string;
  gameId: string;
  game: string;
  partner?: string;
  categoryId: string;
  description: string;
  features: string[];
  specs: { label: string; value: string }[];
  images: string[];
  coverImage?: string;
  galleryImages?: string[];
  priceTiers: PriceTier[];
  status: "undetected" | "detected" | "updating";
  lastUpdate: string;
  createdAt: string;
}

export const games: Game[] = ${JSON.stringify(gamesData, null, 2)};

export const products: Product[] = ${JSON.stringify(productsData, null, 2)};

export const reviews: Review[] = ${JSON.stringify(reviewsData, null, 2)};

// Helper functions
export function getGames(): Game[] {
  return games;
}

export function getGameById(id: string): Game | undefined {
  return games.find(g => g.id === id);
}

export function getFeaturedGames(): Game[] {
  return games.filter(g => g.featured);
}

export function getProducts(): Product[] {
  return products;
}

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getProductsByGame(game: string): Product[] {
  return products.filter(p => p.game === game);
}

export function getProductsByGameId(gameId: string): Product[] {
  return products.filter(p => p.gameId === gameId);
}

export function getReviews(): Review[] {
  return reviews;
}
`;
}

// ========== COMPONENT ==========
export default function AdminPage() {
  const [gameList, setGameList] = useState<Game[]>([...defaultGames]);
  const [productList, setProductList] = useState<Product[]>([...defaultProducts]);
  const [reviewList, setReviewList] = useState<Review[]>([...defaultReviews]);
  const [activeTab, setActiveTab] = useState<"games" | "cheats" | "reviews">("games");

  // Game editing
  const [editGame, setEditGame] = useState<EditGame | null>(null);
  const [isNewGame, setIsNewGame] = useState(false);

  // Product editing
  const [editProd, setEditProd] = useState<EditProduct | null>(null);
  const [isNewProd, setIsNewProd] = useState(false);

  // Review editing
  const [editReview, setEditReview] = useState<EditReview | null>(null);
  const [isNewReview, setIsNewReview] = useState(false);

  // Save status
  const [saveMsg, setSaveMsg] = useState("");

  // Selected game filter for cheats tab
  const [filterGameId, setFilterGameId] = useState("");
  const [filterPartner, setFilterPartner] = useState("");

  const filteredProducts = productList.filter(p => {
    if (filterGameId && p.gameId !== filterGameId) return false;
    if (filterPartner && p.partner !== filterPartner) return false;
    return true;
  });

  // Extract unique partners from the product list
  const uniquePartners = Array.from(new Set(productList.map(p => p.partner).filter(Boolean))) as string[];

  // ========== GAME CRUD ==========
  const openNewGame = () => {
    setEditGame({ id: `game-${Date.now()}`, name: "", image: "", icon: "", featured: false, status: "online", description: "" });
    setIsNewGame(true);
  };

  const openEditGame = (g: Game) => {
    setEditGame({ ...g });
    setIsNewGame(false);
  };

  const saveGame = () => {
    if (!editGame) return;
    if (isNewGame) {
      setGameList(prev => [...prev, editGame]);
    } else {
      setGameList(prev => prev.map(g => g.id === editGame.id ? editGame : g));
      setProductList(prev => prev.map(p =>
        p.gameId === editGame.id ? { ...p, game: editGame.name } : p
      ));
    }
    setEditGame(null);
  };

  const deleteGame = (id: string) => {
    const hasProducts = productList.some(p => p.gameId === id);
    if (hasProducts) {
      alert("Нельзя удалить игру с товарами! Сначала удалите или переместите читы.");
      return;
    }
    if (confirm("Удалить игру?")) {
      setGameList(prev => prev.filter(g => g.id !== id));
    }
  };

  // ========== PRODUCT CRUD ==========
  const openNewProd = (gameId?: string) => {
    const game = gameId ? gameList.find(g => g.id === gameId) : gameList[0];
    setEditProd({
      id: `prod-${Date.now()}`,
      name: "",
      gameId: game?.id || "",
      game: game?.name || "",
      partner: "",
      description: "",
      features: "",
      specs: "ОС: Windows 10 / 11\nCPU: Intel & AMD",
      coverImage: "",
      galleryImages: [],
      priceTiers: [
        { label: "", duration: "1d", price: 500 },
        { label: "", duration: "7d", price: 1500 },
        { label: "", duration: "30d", price: 2500 },
      ],
      status: "undetected",
    });
    setIsNewProd(true);
  };
  const openEditProd = (p: Product) => {
    setEditProd(toEditProduct(p));
    setIsNewProd(false);
  };
  const saveProd = () => {
    if (!editProd) return;
    const game = gameList.find(g => g.id === editProd.gameId);
    const final = fromEditProduct({ ...editProd, game: game?.name || editProd.game });
    if (isNewProd) {
      setProductList(prev => [...prev, final]);
    } else {
      setProductList(prev => prev.map(p => p.id === final.id ? final : p));
    }
    setEditProd(null);
  };
  const deleteProd = (id: string) => {
    if (confirm("Удалить чит?")) {
      setProductList(prev => prev.filter(p => p.id !== id));
    }
  };
  const updateTierPrice = (idx: number, field: keyof PriceTier, value: string | number) => {
    if (!editProd) return;
    const tiers = [...editProd.priceTiers];
    tiers[idx] = { ...tiers[idx], [field]: field === "price" ? Number(value) : value };
    setEditProd({ ...editProd, priceTiers: tiers });
  };
  const addTier = () => {
    if (!editProd) return;
    setEditProd({ ...editProd, priceTiers: [...editProd.priceTiers, { label: "", duration: "1d", price: 0 }] });
  };
  const removeTier = (idx: number) => {
    if (!editProd) return;
    setEditProd({ ...editProd, priceTiers: editProd.priceTiers.filter((_, i) => i !== idx) });
  };

  // ========== REGION PRICING CRUD (REMOVED) ==========

  // ========== REVIEW CRUD ==========
  const openNewReview = () => {
    setEditReview({ id: `rev-${Date.now()}`, author: "", rating: 5, text: "" });
    setIsNewReview(true);
  };
  const openEditReview = (r: Review) => {
    setEditReview({ id: r.id, author: r.author, rating: r.rating, text: r.text });
    setIsNewReview(false);
  };
  const saveReview = () => {
    if (!editReview) return;
    const rev: Review = { ...editReview, createdAt: new Date().toISOString() };
    if (isNewReview) {
      setReviewList(prev => [...prev, rev]);
    } else {
      setReviewList(prev => prev.map(r => r.id === rev.id ? rev : r));
    }
    setEditReview(null);
  };
  const deleteReview = (id: string) => {
    if (confirm("Удалить отзыв?")) {
      setReviewList(prev => prev.filter(r => r.id !== id));
    }
  };

  // ========== SAVE DATA TO SERVER ==========
  const saveDataToServer = async () => {
    try {
      setSaveMsg("⏳ Сохранение...");
      const response = await fetch('/api/save-data', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          games: gameList,
          products: productList,
          reviews: reviewList,
        }),
      });

      if (!response.ok) {
        throw new Error('Network response was not ok');
      }

      setSaveMsg("✅ Данные успешно сохранены на сервере!");
    } catch (error) {
      console.error('Error saving data:', error);
      setSaveMsg("❌ Ошибка при сохранении данных на сервер.");
    }
  };

  // ========== RENDER ==========
  return (
    <div className="min-h-screen pt-24 pb-12 bg-black/95">
      <div className="max-w-7xl mx-auto px-4 sm:px-6">

        {/* Header */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 mb-8">
          <div>
            <h1 className="text-3xl font-black text-white">⚙️ ADMIN PANEL</h1>
            <p className="text-sm text-gray-500 mt-1">Отредактируй данные и нажми кнопку для сохранения на сервере.</p>
          </div>
          <div className="flex gap-3">
            <button
              onClick={saveDataToServer}
              className="px-6 py-3 rounded-xl bg-green-600 hover:bg-green-500 text-white font-bold transition-all shadow-lg shadow-green-600/20"
            >
              💾 СОХРАНИТЬ НА СЕРВЕР
            </button>
          </div>
        </div>

        {saveMsg && (
          <div className={`mb-6 p-4 rounded-xl border text-sm font-medium ${saveMsg.includes("✅") || saveMsg.includes("🔄")
            ? "bg-green-500/10 border-green-500/30 text-green-400"
            : "bg-red-500/10 border-red-500/30 text-red-400"
            }`}>
            {saveMsg}
          </div>
        )}

        {/* Auto-save indicator */}
        <div className="mb-6 p-3 rounded-xl bg-blue-500/5 border border-blue-500/20 text-xs text-blue-400 font-medium flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-blue-400 animate-pulse" />
          Все изменения автоматически сохраняются в localStorage браузера
        </div>

        {/* Stats */}
        <div className="grid grid-cols-4 gap-4 mb-8">
          <div className="glass-panel p-6 text-center">
            <div className="text-3xl font-black text-white">{gameList.length}</div>
            <div className="text-sm text-gray-400 mt-1">Игр</div>
          </div>
          <div className="glass-panel p-6 text-center">
            <div className="text-3xl font-black text-white">{productList.length}</div>
            <div className="text-sm text-gray-400 mt-1">Читов</div>
          </div>
          <div className="glass-panel p-6 text-center">
            <div className="text-3xl font-black text-[var(--color-primary)]">
              {productList.filter(p => p.status === "undetected").length}
            </div>
            <div className="text-sm text-gray-400 mt-1">Undetected</div>
          </div>
          <div className="glass-panel p-6 text-center">
            <div className="text-3xl font-black text-yellow-400">{reviewList.length}</div>
            <div className="text-sm text-gray-400 mt-1">Отзывов</div>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex gap-2 mb-6 border-b border-white/10 pb-4">
          <button
            onClick={() => setActiveTab("games")}
            className={`px-5 py-2.5 rounded-lg font-bold text-sm transition-all ${activeTab === "games"
              ? "bg-[var(--color-primary)] text-white"
              : "bg-white/5 text-gray-400 hover:bg-white/10"
              }`}
          >
            🎮 Игры
          </button>
          <button
            onClick={() => setActiveTab("cheats")}
            className={`px-5 py-2.5 rounded-lg font-bold text-sm transition-all ${activeTab === "cheats"
              ? "bg-[var(--color-primary)] text-white"
              : "bg-white/5 text-gray-400 hover:bg-white/10"
              }`}
          >
            🔫 Читы
          </button>
          <button
            onClick={() => setActiveTab("reviews")}
            className={`px-5 py-2.5 rounded-lg font-bold text-sm transition-all ${activeTab === "reviews"
              ? "bg-[var(--color-primary)] text-white"
              : "bg-white/5 text-gray-400 hover:bg-white/10"
              }`}
          >
            ⭐ Отзывы
          </button>
        </div>

        {/* =================== GAMES TAB =================== */}
        {activeTab === "games" && (
          <>
            <div className="mb-4">
              <button onClick={openNewGame} className="px-5 py-2.5 rounded-lg bg-[var(--color-primary)] hover:bg-[var(--color-secondary)] text-white font-bold transition-all">
                ➕ Добавить игру
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {gameList.map(g => {
                const cheatCount = productList.filter(p => p.gameId === g.id).length;
                return (
                  <div key={g.id} className="glass-panel p-5 space-y-3 hover:border-[var(--color-primary)]/30 transition-colors">
                    <div className="flex items-center gap-3">
                      {g.image ? (
                        <img src={g.image} alt={g.name} className="w-12 h-12 rounded-lg object-cover border border-white/10" />
                      ) : (
                        <div className="w-12 h-12 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center text-2xl">🎮</div>
                      )}
                      <div className="flex-1">
                        <h3 className="text-lg font-bold text-white">{g.name}</h3>
                        <div className="flex items-center gap-2 text-xs text-gray-500">
                          <span>{cheatCount} читов</span>
                          {g.featured && <span className="px-1.5 py-0.5 rounded bg-yellow-500/20 text-yellow-400 font-bold">⭐ Актуальная</span>}
                        </div>
                      </div>
                      <span className={`text-xs px-2 py-1 rounded-full font-bold uppercase ${g.status === "online"
                        ? "bg-green-500/20 text-green-400"
                        : g.status === "updating"
                          ? "bg-yellow-500/20 text-yellow-400"
                          : "bg-red-500/20 text-red-400"
                        }`}>
                        {g.status}
                      </span>
                    </div>
                    {g.description && <div className="text-sm text-gray-400 truncate">{g.description}</div>}
                    <div className="flex gap-2 pt-2 border-t border-white/5">
                      <button onClick={() => openEditGame(g)} className="flex-1 px-3 py-2 rounded-lg bg-blue-500/10 text-blue-400 font-bold text-sm hover:bg-blue-500/20">
                        ✏️
                      </button>
                      <button
                        onClick={() => { setActiveTab("cheats"); setFilterGameId(g.id); }}
                        className="flex-1 px-3 py-2 rounded-lg bg-purple-500/10 text-purple-400 font-bold text-sm hover:bg-purple-500/20"
                      >
                        🔫 Читы
                      </button>
                      <button onClick={() => deleteGame(g.id)} className="px-3 py-2 rounded-lg bg-red-500/10 text-red-400 font-bold text-sm hover:bg-red-500/20">
                        🗑️
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          </>
        )}

        {/* =================== CHEATS TAB =================== */}
        {activeTab === "cheats" && (
          <>
            <div className="flex flex-wrap items-center gap-4 mb-4">
              <button onClick={() => openNewProd(filterGameId || undefined)} className="px-5 py-2.5 rounded-lg bg-[var(--color-primary)] hover:bg-[var(--color-secondary)] text-white font-bold transition-all">
                ➕ Добавить чит
              </button>
              <select
                value={filterGameId}
                onChange={e => setFilterGameId(e.target.value)}
                className="px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white font-medium"
              >
                <option value="">Все игры</option>
                {gameList.map(g => (
                  <option key={g.id} value={g.id}>{g.name}</option>
                ))}
              </select>
              <select
                value={filterPartner}
                onChange={e => setFilterPartner(e.target.value)}
                className="px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white font-medium"
              >
                <option value="">Все партнеры</option>
                {uniquePartners.map(partner => (
                  <option key={partner} value={partner}>{partner}</option>
                ))}
              </select>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {filteredProducts.map(p => (
                <div key={p.id} className="glass-panel p-5 space-y-3 hover:border-[var(--color-primary)]/30 transition-colors">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      {p.coverImage ? (
                        <img src={p.coverImage} alt={p.name} className="w-10 h-10 rounded-lg object-cover border border-white/10" />
                      ) : (
                        <div className="w-10 h-10 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center text-lg">🔫</div>
                      )}
                      <div>
                        <h3 className="text-lg font-bold text-white">{p.name}</h3>
                        <div className="text-xs text-gray-500">
                          {p.game}
                          {p.partner && <span className="ml-2 px-1.5 py-0.5 rounded bg-blue-500/20 text-blue-400">👤 {p.partner}</span>}
                        </div>
                      </div>
                    </div>
                    <span className={`text-xs px-2 py-1 rounded-full font-bold uppercase ${p.status === "undetected"
                      ? "bg-green-500/20 text-green-400"
                      : p.status === "updating"
                        ? "bg-yellow-500/20 text-yellow-400"
                        : "bg-red-500/20 text-red-400"
                      }`}>
                      {p.status}
                    </span>
                  </div>
                  <div className="text-sm text-gray-400 truncate">{p.description}</div>
                  <div className="flex flex-wrap gap-1">
                    {p.priceTiers.map((t, i) => (
                      <span key={i} className="text-xs bg-white/5 px-2 py-1 rounded text-gray-300">
                        {t.label}: {t.price}₽
                      </span>
                    ))}
                  </div>
                  <div className="flex gap-2 pt-2 border-t border-white/5">
                    <button onClick={() => openEditProd(p)} className="flex-1 px-3 py-2 rounded-lg bg-blue-500/10 text-blue-400 font-bold text-sm hover:bg-blue-500/20">
                      ✏️ Ред.
                    </button>
                    <button onClick={() => deleteProd(p.id)} className="px-3 py-2 rounded-lg bg-red-500/10 text-red-400 font-bold text-sm hover:bg-red-500/20">
                      🗑️
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </>
        )}

        {/* =================== REVIEWS TAB =================== */}
        {activeTab === "reviews" && (
          <>
            <div className="mb-4">
              <button onClick={openNewReview} className="px-5 py-2.5 rounded-lg bg-[var(--color-primary)] hover:bg-[var(--color-secondary)] text-white font-bold transition-all">
                ➕ Добавить отзыв
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {reviewList.map(r => (
                <div key={r.id} className="glass-panel p-5 space-y-3 hover:border-[var(--color-primary)]/30 transition-colors">
                  <div className="flex items-center justify-between">
                    <h3 className="text-lg font-bold text-white">{r.author}</h3>
                    <div className="flex gap-0.5">
                      {Array.from({ length: 5 }).map((_, i) => (
                        <span key={i} className={`text-sm ${i < r.rating ? "text-yellow-400" : "text-gray-600"}`}>★</span>
                      ))}
                    </div>
                  </div>
                  <p className="text-sm text-gray-400 line-clamp-3">{r.text}</p>
                  <div className="flex gap-2 pt-2 border-t border-white/5">
                    <button onClick={() => openEditReview(r)} className="flex-1 px-3 py-2 rounded-lg bg-blue-500/10 text-blue-400 font-bold text-sm hover:bg-blue-500/20">
                      ✏️ Ред.
                    </button>
                    <button onClick={() => deleteReview(r.id)} className="px-3 py-2 rounded-lg bg-red-500/10 text-red-400 font-bold text-sm hover:bg-red-500/20">
                      🗑️
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </>
        )}

        {/* =================== MODALS =================== */}
        {/* Game Modal */}
        {editGame && (
          <>
            <div className="fixed inset-0 bg-black/80 z-50 backdrop-blur-sm" onClick={() => setEditGame(null)} />
            <div className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-50 w-[90vw] max-w-lg bg-[#1a1a1f] border border-white/10 rounded-2xl p-6 shadow-2xl">
              <h2 className="text-2xl font-black text-white mb-6">
                {isNewGame ? "➕ Новая игра" : "✏️ Редактирование игры"}
              </h2>
              <div className="space-y-4">
                <div>
                  <label className="text-sm text-gray-400 font-bold block mb-1">Название</label>
                  <input value={editGame.name} onChange={e => setEditGame({ ...editGame, name: e.target.value })} className="w-full px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white" />
                </div>
                <div>
                  <label className="text-sm text-gray-400 font-bold block mb-1">Обложка (URL)</label>
                  <input value={editGame.image} onChange={e => setEditGame({ ...editGame, image: e.target.value })} className="w-full px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white" />
                </div>
                <div>
                  <label className="text-sm text-gray-400 font-bold block mb-1">Иконка для «Актуальные» (URL)</label>
                  <input value={editGame.icon} onChange={e => setEditGame({ ...editGame, icon: e.target.value })} className="w-full px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white" placeholder="URL иконки для сайдбара актуальных игр" />
                </div>
                <div className="flex items-center gap-3">
                  <input
                    type="checkbox"
                    checked={editGame.featured}
                    onChange={e => setEditGame({ ...editGame, featured: e.target.checked })}
                    className="w-5 h-5 rounded border-white/20 bg-white/5 accent-[var(--color-primary)]"
                  />
                  <label className="text-sm text-gray-300 font-bold">⭐ Показывать в «Актуальные игры» на главной</label>
                </div>
                <div>
                  <label className="text-sm text-gray-400 font-bold block mb-1">Статус</label>
                  <select value={editGame.status} onChange={e => setEditGame({ ...editGame, status: e.target.value as "online" | "offline" | "updating" })} className="w-full px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white">
                    <option value="online">ONLINE</option>
                    <option value="updating">UPDATING</option>
                    <option value="offline">OFFLINE</option>
                  </select>
                </div>
                <div>
                  <label className="text-sm text-gray-400 font-bold block mb-1">Описание</label>
                  <textarea value={editGame.description} onChange={e => setEditGame({ ...editGame, description: e.target.value })} className="w-full px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white" rows={3} />
                </div>
              </div>
              <div className="flex gap-3 mt-6 pt-4 border-t border-white/10">
                <button onClick={() => setEditGame(null)} className="flex-1 py-3 rounded-xl bg-white/5 text-gray-400 font-bold hover:bg-white/10">Отмена</button>
                <button onClick={saveGame} className="flex-1 py-3 rounded-xl bg-[var(--color-primary)] text-white font-bold hover:bg-[var(--color-secondary)]">💾 Сохранить</button>
              </div>
            </div>
          </>
        )}

        {/* Product Modal */}
        {editProd && (
          <>
            <div className="fixed inset-0 bg-black/80 z-50 backdrop-blur-sm" onClick={() => setEditProd(null)} />
            <div className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-50 w-[90vw] max-w-2xl max-h-[85vh] overflow-y-auto bg-[#1a1a1f] border border-white/10 rounded-2xl p-6 shadow-2xl">
              <h2 className="text-2xl font-black text-white mb-6">
                {isNewProd ? "➕ Новый чит" : "✏️ Редактирование чита"}
              </h2>
              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm text-gray-400 font-bold block mb-1">Название</label>
                    <input value={editProd.name} onChange={e => setEditProd({ ...editProd, name: e.target.value })} className="w-full px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white" />
                  </div>
                  <div>
                    <label className="text-sm text-gray-400 font-bold block mb-1">Игра</label>
                    <select value={editProd.gameId} onChange={e => { const g = gameList.find(g => g.id === e.target.value); setEditProd({ ...editProd, gameId: e.target.value, game: g?.name || "" }); }} className="w-full px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white">
                      <option value="">-- Выбрать --</option>
                      {gameList.map(g => (<option key={g.id} value={g.id}>{g.name}</option>))}
                    </select>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm text-gray-400 font-bold block mb-1">Партнер</label>
                    <input value={editProd.partner || ""} onChange={e => setEditProd({ ...editProd, partner: e.target.value })} className="w-full px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white" placeholder="Имя партнера (опционально)" />
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm text-gray-400 font-bold block mb-1">Статус</label>
                    <select value={editProd.status} onChange={e => setEditProd({ ...editProd, status: e.target.value as "undetected" | "detected" | "updating" })} className="w-full px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white">
                      <option value="undetected">UNDETECTED</option>
                      <option value="updating">UPDATING</option>
                      <option value="detected">DETECTED</option>
                    </select>
                  </div>
                  <div>
                    <label className="text-sm text-gray-400 font-bold block mb-1">📷 Обложка (PNG)</label>
                    {editProd.coverImage ? (
                      <div className="relative inline-block">
                        <img src={editProd.coverImage} alt="Cover" className="w-full h-24 object-cover rounded-lg border border-white/10" />
                        <button
                          onClick={() => setEditProd({ ...editProd, coverImage: "" })}
                          className="absolute top-1 right-1 w-6 h-6 rounded-full bg-red-500 text-white text-xs flex items-center justify-center hover:bg-red-400"
                        >✕</button>
                      </div>
                    ) : (
                      <label className="flex flex-col items-center justify-center w-full h-24 rounded-lg border-2 border-dashed border-white/20 hover:border-[var(--color-primary)]/50 cursor-pointer transition-colors bg-white/5">
                        <span className="text-2xl mb-1">📤</span>
                        <span className="text-xs text-gray-500">Нажми чтобы загрузить PNG</span>
                        <input
                          type="file"
                          accept=".png,image/png"
                          className="hidden"
                          onChange={(e) => {
                            const file = e.target.files?.[0];
                            if (!file) return;
                            const reader = new FileReader();
                            reader.onload = () => {
                              setEditProd({ ...editProd, coverImage: reader.result as string });
                            };
                            reader.readAsDataURL(file);
                          }}
                        />
                      </label>
                    )}
                  </div>
                </div>
                <div>
                  <label className="text-sm text-gray-400 font-bold block mb-2">Тарифы</label>
                  <div className="space-y-2">
                    {editProd.priceTiers.map((tier, i) => (
                      <div key={i} className="flex gap-2 items-center">
                        <input value={tier.duration} onChange={e => updateTierPrice(i, "duration", e.target.value)} className="w-24 px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white text-sm" placeholder="7d" />

                        <input type="number" value={tier.price} onChange={e => updateTierPrice(i, "price", e.target.value)} className="flex-1 px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white text-sm" placeholder="RUB Цена" />
                        <span className="text-gray-500 text-xs">₽</span>

                        <input type="number" step="0.01" value={tier.priceUsd ?? ""} onChange={e => updateTierPrice(i, "priceUsd", e.target.value ? Number(e.target.value) : undefined as any)} className="flex-1 px-3 py-2 rounded-lg bg-white/5 border border-white/10 text-white text-sm" placeholder="World (USD)" />
                        <span className="text-gray-500 text-xs">$</span>

                        <button onClick={() => removeTier(i)} className="text-red-400 hover:text-red-300 ml-2">✕</button>
                      </div>
                    ))}
                    <p className="text-[10px] text-gray-600 mt-1">Формат длительности: 1d, 7d, 30d, lifetime. Доллары опциональны, но нужны для региона "World".</p>
                    <button onClick={addTier} className="text-sm text-[var(--color-primary)] hover:underline">+ Добавить тариф</button>
                  </div>
                </div>
                <div>
                  <label className="text-sm text-gray-400 font-bold block mb-1">Описание</label>
                  <textarea value={editProd.description} onChange={e => setEditProd({ ...editProd, description: e.target.value })} rows={3} className="w-full px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white" />
                </div>
                <div>
                  <label className="text-sm text-gray-400 font-bold block mb-1">Функции (каждая с новой строки)</label>
                  <textarea value={editProd.features} onChange={e => setEditProd({ ...editProd, features: e.target.value })} rows={3} className="w-full px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white" placeholder={"Aimbot\nESP"} />
                </div>
                <div>
                  <label className="text-sm text-gray-400 font-bold block mb-1">Характеристики</label>
                  <textarea value={editProd.specs} onChange={e => setEditProd({ ...editProd, specs: e.target.value })} rows={3} className="w-full px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white" placeholder={"ОС: Windows 10\nCPU: Intel"} />
                </div>
                {/* Gallery Images Upload */}
                <div>
                  <label className="text-sm text-gray-400 font-bold block mb-2">🖼️ Галерея (PNG/MP4/WEBM) <span className="text-xs text-gray-600 font-normal">— фото и видео для страницы товара</span></label>
                  <div className="flex flex-wrap gap-2 mb-2">
                    {editProd.galleryImages.map((img, idx) => {
                      const isVideo = img.startsWith('data:video/') || img.endsWith('.mp4') || img.endsWith('.webm') || img.endsWith('.mov');
                      return (
                        <div key={idx} className="relative w-20 h-20 rounded-lg overflow-hidden border border-white/10 group bg-black/50">
                          {isVideo ? (
                            <div className="w-full h-full flex items-center justify-center">
                              <Play className="w-8 h-8 text-white/50 fill-current" />
                            </div>
                          ) : (
                            <img src={img} alt={`Gallery ${idx}`} className="w-full h-full object-cover" />
                          )}
                          <button
                            type="button"
                            onClick={(e) => {
                              e.preventDefault();
                              e.stopPropagation();
                              setEditProd({ ...editProd, galleryImages: editProd.galleryImages.filter((_, i) => i !== idx) });
                            }}
                            className="absolute top-0.5 right-0.5 z-10 w-5 h-5 rounded-full bg-red-500 text-white text-[10px] flex justify-center items-center opacity-0 group-hover:opacity-100 transition-opacity hover:bg-red-400"
                          >✕</button>
                        </div>
                      )
                    })}
                    <label className="w-20 h-20 rounded-lg border-2 border-dashed border-white/20 hover:border-[var(--color-primary)]/50 cursor-pointer transition-colors bg-white/5 flex flex-col items-center justify-center">
                      <span className="text-xl">+</span>
                      <span className="text-[9px] text-gray-500 text-center px-1">Медиа</span>
                      <input
                        type="file"
                        accept="image/*,video/mp4,video/webm"
                        multiple
                        className="hidden"
                        onChange={async (e) => {
                          const files = e.target.files;
                          if (!files || files.length === 0) return;

                          setSaveMsg("⏳ Загрузка файлов...");

                          for (let i = 0; i < files.length; i++) {
                            const file = files[i];
                            const formData = new FormData();
                            formData.append("file", file);

                            try {
                              const response = await fetch('/api/upload', {
                                method: 'POST',
                                body: formData,
                              });

                              if (response.ok) {
                                const data = await response.json();
                                if (data.success) {
                                  setEditProd(prev => {
                                    if (!prev) return prev;
                                    return {
                                      ...prev,
                                      galleryImages: [...prev.galleryImages, data.url]
                                    };
                                  });
                                }
                              }
                            } catch (err) {
                              console.error("Error uploading file", err);
                              alert(`Ошибка при загрузке ${file.name}`);
                            }
                          }

                          setSaveMsg("");
                        }}
                      />
                    </label>
                  </div>
                  <p className="text-[10px] text-gray-600">Можно загрузить несколько PNG файлов. Эти фото видны только на странице товара.</p>
                </div>
              </div>
              <div className="flex gap-3 mt-6 pt-4 border-t border-white/10">
                <button onClick={() => setEditProd(null)} className="flex-1 py-3 rounded-xl bg-white/5 text-gray-400 font-bold hover:bg-white/10">Отмена</button>
                <button onClick={saveProd} className="flex-1 py-3 rounded-xl bg-[var(--color-primary)] text-white font-bold hover:bg-[var(--color-secondary)]">💾 Сохранить</button>
              </div>
            </div>
          </>
        )}

        {/* Review Modal */}
        {editReview && (
          <>
            <div className="fixed inset-0 bg-black/80 z-50 backdrop-blur-sm" onClick={() => setEditReview(null)} />
            <div className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 z-50 w-[90vw] max-w-lg bg-[#1a1a1f] border border-white/10 rounded-2xl p-6 shadow-2xl">
              <h2 className="text-2xl font-black text-white mb-6">
                {isNewReview ? "➕ Новый отзыв" : "✏️ Редактирование отзыва"}
              </h2>
              <div className="space-y-4">
                <div>
                  <label className="text-sm text-gray-400 font-bold block mb-1">Автор</label>
                  <input value={editReview.author} onChange={e => setEditReview({ ...editReview, author: e.target.value })} className="w-full px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white" />
                </div>
                <div>
                  <label className="text-sm text-gray-400 font-bold block mb-2">Рейтинг</label>
                  <div className="flex gap-2">
                    {[1, 2, 3, 4, 5].map(n => (
                      <button
                        key={n}
                        onClick={() => setEditReview({ ...editReview, rating: n })}
                        className={`text-2xl transition-all ${n <= editReview.rating ? "text-yellow-400 scale-110" : "text-gray-600 hover:text-yellow-300"}`}
                      >
                        ★
                      </button>
                    ))}
                  </div>
                </div>
                <div>
                  <label className="text-sm text-gray-400 font-bold block mb-1">Текст отзыва</label>
                  <textarea value={editReview.text} onChange={e => setEditReview({ ...editReview, text: e.target.value })} className="w-full px-4 py-2.5 rounded-lg bg-white/5 border border-white/10 text-white" rows={4} />
                </div>
              </div>
              <div className="flex gap-3 mt-6 pt-4 border-t border-white/10">
                <button onClick={() => setEditReview(null)} className="flex-1 py-3 rounded-xl bg-white/5 text-gray-400 font-bold hover:bg-white/10">Отмена</button>
                <button onClick={saveReview} className="flex-1 py-3 rounded-xl bg-[var(--color-primary)] text-white font-bold hover:bg-[var(--color-secondary)]">💾 Сохранить</button>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
